// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearUnpinned():Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetActivationKey():Promise<string>;

export function GetClipData():Promise<Array<main.ClipItem>>;

export function HidePanel():Promise<void>;

export function PasteText(arg1:string):Promise<void>;

export function ReregisterHotkey(arg1:string,arg2:number,arg3:number):Promise<boolean>;

export function SavePrompt(arg1:string):Promise<void>;

export function ShowPanel():Promise<void>;

export function TogglePanel():Promise<void>;

export function TogglePin(arg1:string):Promise<void>;
