// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearUnpinned() {
  return window['go']['main']['App']['ClearUnpinned']();
}

export function GetActivationKey() {
  return window['go']['main']['App']['GetActivationKey']();
}

export function GetClipData() {
  return window['go']['main']['App']['GetClipData']();
}

export function HidePanel() {
  return window['go']['main']['App']['HidePanel']();
}

export function PasteText(arg1) {
  return window['go']['main']['App']['PasteText'](arg1);
}

export function ReregisterHotkey(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReregisterHotkey'](arg1, arg2, arg3);
}

export function SavePrompt(arg1) {
  return window['go']['main']['App']['SavePrompt'](arg1);
}

export function ShowPanel() {
  return window['go']['main']['App']['ShowPanel']();
}

export function TogglePanel() {
  return window['go']['main']['App']['TogglePanel']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}
